### ISSUE TITLE
suggestion: srt file being named the same as the mkv

### ISSUE THREAD

**Issue by Alexprox7** [qgustavor/mkv-extract#23] opened 2022-08-20 09:28 UTC
hi, thank you for this amazing project; I would like to ask a thing or two; can you make it so that the srt file is named the same as the video he is extracted from? some old tvs require this to happen to view subtitles correctly and would slightly speed some actions. in case you did that, i would also suggest leaving all the srt in the same folder for multiple extracts at the same time(they are now distinguishable) thank you.

**Comment by qgustavor** [comment] 2022-08-20 14:13
It might be implemented along #21, since gMKVExtractGUI allows you to set patterns for the file names (subtitles default to `{FilenameNoExt}_track{TrackNumber}_[{Language}]` in the version I use).

As I said in the other issue, I don't want to implement new features using the current codebase. To be fair, while I said in April that I use this tool, nowadays I just use it in platforms where gMKVExtractGUI is not supported, as an example, if I download something in my phone, I want to fix a subtitle that's really messed up and I don't want to wait until I get home for that. In the other cases I just use gMKVExtractGUI.

This project was an experiment in order to just test if I could find a way to play .mkv in browsers. At that time I was working on [direct-mega](https://github.com/qgustavor/direct-mega/tree/8897b53f2e547dd0948cb4923a7c1ed51ebaf3b6) and there were some groups that were publishing files via MEGA using .mkv files. Nowadays many groups stopped using MEGA, I don't watch those groups, some don't even exist anymore, some browsers can reproduce .mkv files, so this project is just a leftover of that time. The implementation is a mess because it's just what it was intended to be, an experiment.

I don't want to implement new features. In the other hand you are free to check the code, fix the mess, split it into some modules or even remove almost everything and replace with [matroska-subtitles](https://github.com/mathiasvr/matroska-subtitles), add a GUI to customize filename patterns then send a pull request.

**Comment by qgustavor** [comment] 2022-08-31 03:23
Closing in favor of #21.

**Closed as not planned by qgustavor** 2022-08-31 03:23 UTC
