### ISSUE TITLE
Can't extract

### ISSUE THREAD

**Issue by Trentoast** [qgustavor/mkv-extract#41] opened 2024-05-27 04:45 UTC
I have been trying to extract subtitles, so I can turn them yellow I notice that's it taking longer I came back 10 minutes later, but it's still not extracting

**Comment by qgustavor** [comment] 2024-05-27 11:05
I can reproduce. It might be related to the last update. I will look into that.

**Comment by qgustavor** [comment] 2024-05-27 13:17
It should be fixed as for cc649fb. It was a path related bug introduced after i18n implementation because of the changes of the paths (also I'm quite annoyed at sveltekit-i18n, implementing it led to so many issues and documentation there is not good).

**Comment by Trentoast** [comment] 2024-05-27 14:36
It worked thank you so much

**Closed as completed** 2024-05-27 15:13 UTC
